services:
  meta_service:
    depends_on:
      pd:
        condition: service_started
      tikv:
        condition: service_started

  pd:
    image: pingcap/pd:v7.5.0
    command:
      - /pd-server
      - --name=pd
      - --data-dir=/var/lib/pd
      - --client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://pd:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-peer-urls=http://pd:2380
      - --initial-cluster=pd=http://pd:2380
      - --log-level=info
    restart: on-failure
    volumes:
      - tikv_pd_data:/var/lib/pd
    networks:
      - storage_net

  tikv:
    image: pingcap/tikv:v7.5.0
    command:
      - /tikv-server
      - --pd=pd:2379
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --status-addr=0.0.0.0:20180
      - --data-dir=/var/lib/tikv
      - --log-level=info
    depends_on:
      - pd
    restart: on-failure
    volumes:
      - tikv_store_data:/var/lib/tikv
    networks:
      - storage_net

volumes:
  tikv_pd_data:
  tikv_store_data:
