apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../k3s/base

patches:
  - path: api-load-balancer.yaml
  - path: storage-node-required-anti-affinity.yaml
  - path: quota-friendly-storage.yaml
