apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-node
spec:
  template:
    spec:
      nodeSelector:
        rec-store-role: storage
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: storage-node
              topologyKey: kubernetes.io/hostname
